SMS/urls.py
from django.urls import path

from . import views

app_name = 'SMS'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='About'),
    path('student/<int:student_id>/', views.student, name = 'student'),
    path('articles/', views.articles, name = 'Articles'),
    path('contact_us/', views.contact_us, name = 'Contact_Us'),
    path('sitemaps/', views.site_map, name = 'Sitemaps'),
    path('login/', views.login , name = 'Login'),
    path('student/<int:student_id>/timetable/', views.view_student_timetable, name ='ViewTimeTableSudent'),
    path('student/<int:student_id>/AcademicDetail/', views.view_student_academic_detail, name = 'StudentAcademicDetail'),
    path('student/<int:student_id>/ViewDateSheet/' , views.view_date_sheet ,name = 'ViewDateSheet'),
    path('student/<int:student_id>/ViewResult/' , views.view_result ,name = 'ViewResult'),
    path('student/<int:student_id>/SendStudentRequest/' , views.send_student_request ,name = 'SendStudentRequest'),
    path('student/<int:student_id>/UploadStudentAssignment/' , views.upload_student_assignment ,name = 'UploadStudentAssignment'),
    path('student/<int:student_id>/ViewStudentFee/' , views.view_student_fee ,name = 'ViewStudentFee'),

    path('teacher/<int:teacher_id>', views.teacher_dashboard, name = 'Teacher'),
    path('teacher/<int:teacher_id>/timetabe/', views.teacher_timetable, name = 'TeacherTimeTable'),
    path('teacher/<int:teacher_id>/assignments/', views.teacher_upload_assignments, name = 'TeacherAssignments'),
    path('teacher/<int:teacher_id>/attendance/', views.teacher_attendance, name = 'TeacherAttendance'),
    path('teacher/<int:teacher_id>/payroll/', views.teacher_payroll, name = 'TeacherPayroll'),
    path('teacher/<int:teacher_id>/request/', views.teacher_request, name = 'TeacherRequest'),
    path('teacher/<int:teacher_id>/result/', views.teacher_result, name = 'TeacherResult'),
    path('GeneratePDF/', views.GeneratePDF, name = 'FeeChallan'),
]

SMS/templates/SMS/Assignments.html
<title>Student's Site | Student Home</title>
{% extends "SMS/base.html" %}
{% block content %}
{% load static %}
<div class="container">
<aside>
    <h3>Categories</h3>
    <ul class="categories">
        <li><a href= "{% url 'SMS:ViewTimeTableSudent' StudentId %}" class="m1">Time Table</a></li>
        <li><a href= "{% url 'SMS:ViewDateSheet' StudentId %}" class="m2">Date Sheet</a></li>
        <li><a href= "{% url 'SMS:ViewResult' StudentId %}" class="m3">Result</a></li>
        <li><a href= "{% url 'SMS:SendStudentRequest' StudentId %}" class="m4">Request</a></li>
        <li><a href= "{% url 'SMS:UploadStudentAssignment' StudentId %}" class="m5">Assignments</a></li>
        <li><a href= "{% url 'SMS:StudentAcademicDetail' StudentId %}" class="m6">Academic Detail</a></li>
        <li><a href= "{% url 'SMS:ViewStudentFee'  StudentId%}" class="m7">Fee</a></li>
    </ul>
    </aside>
    <section id="content">
    <div class="inside">
      <h2>Assignments <span>Detail</span></h2>

      <form id="contacts-form" action="#">
        <fieldset>
            <label>choose File:</label>
            <input type="file" on/>
            
          <button type="button"  align = "centre">SUBMIT</button>
          
      </fieldset>
      </form>
      </div>
      </section>
      
      
    </div>
 {% endblock %}

SMS/templates/SMS/AssignmentsT.html
    <div class="container">
      <h1><a href="#">Teacher's site</a></h1>
      <nav>
        <ul>
          <li class="current"><a href="TimeTableT.html" class="m1">Time Table</a></li>
                      <li><a href="DateSheetT.html" class="m2">Date Sheet</a></li>
                      <li><a href="ResultT.html" class="m3">Result</a></li>
                      <li><a href="RequestT.html" class="m4">Request</a></li>
                      <li><a href="AssignmentsT.html" class="m5">Assignments</a></li>
                     
                      <li><a href="Payroll.html" class="m7">Payroll</a></li>
                      <li><a href="AttendanceT.html" class="m8">Attendance</a></li>
                   
                   
        </ul>
      </nav>
    </div>

<h2>Assignments <span>Detail</span></h2>
<form id="contacts-form" action="#">
  <fieldset>
    <div class="field">
      <label>choose File:</label>
      <input type="text" value="" style="width:134px"/>
    </div>

    <button type="button"  align = "centre">Upload</button>
    <button type="button"  align = "centre">Back</button>
    
</fieldset>
</form>

SMS/templates/SMS/AttendanceT.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Teacher's Site | Teacher Home</title>
<meta charset="utf-8">
<link rel="stylesheet" href="css/reset.css" type="text/css" media="all">
<link rel="stylesheet" href="css/style.css" type="text/css" media="all">
<script type="text/javascript" src="js/jquery-1.4.2.min.js" ></script>
<script type="text/javascript" src="js/cufon-yui.js"></script>
<script type="text/javascript" src="js/cufon-replace.js"></script>
<script type="text/javascript" src="js/Myriad_Pro_300.font.js"></script>
<script type="text/javascript" src="js/Myriad_Pro_400.font.js"></script>
<script type="text/javascript" src="js/script.js"></script>
</head>
<body id="page5">
<!-- START PAGE SOURCE -->
<div class="wrap">
  <header>
    <div class="container">
      <h1><a href="#">Teacher's site</a></h1>
      <nav>
        <ul>
            <li class="current"><a href="TimeTableT.html" class="m1">Time Table</a></li>
            <li><a href="DateSheetT.html" class="m2">Date Sheet</a></li>
            <li><a href="ResultT.html" class="m3">Result</a></li>
            <li><a href="RequestT.html" class="m4">Request</a></li>
            <li><a href="AssignmentsT.html" class="m5">Assignments</a></li>
           
            <li><a href="Payroll.html" class="m7">Payroll</a></li>
            <li><a href="AttendanceT.html" class="m8">Attendance</a></li>
         
        </ul>
      </nav>
    </div>
</header>
<h2>Student's <span>Attendance</span></h2>
<form id="contacts-form" action="#">
    <fieldset>
        <div class="field">
       
            <label>Class:</label>
            <input type="text" value=""/>
            <br>
            <label>Section:</label>
            <input type="text" value=""/>
        </div>
        <br></br>
        <table border="2" cellspacing="3" align="left">
            <tr>
                <td align="center">Registration Number
                <td align="center">Status
                
               </tr>
               <tr>
                <td align="center">
                    <td align="center"><font color="black"><br><select>
                     <option value="Present"> P</option>
                     <option value="Absent"> A</option>
                   
               </tr>
               <tr>
                   <td align="center">
                   <td align="center"><font color="black"><br><select>
                    <option value="Present"> P</option>
                    <option value="Absent"> A</option>
                </select>
               </tr>
               <tr>
                <td align="center">
                    <td align="center"><font color="black"><br><select>
                     <option value="Present"> P</option>
                     <option value="Absent"> A</option>
               </tr>
               <tr>
                <td align="center">
                    <td align="center"><font color="black"><br><select>
                     <option value="Present"> P</option>
                     <option value="Absent"> A</option>
               </tr>
               <tr>
                <td align="center">
                    <td align="center"><font color="black"><br><select>
                     <option value="Present"> P</option>
                     <option value="Absent"> A</option>
               </tr>
               <tr>
                <td align="center">
                    <td align="center"><font color="black"><br><select>
                     <option value="Present"> P</option>
                     <option value="Absent"> A</option>
               </tr>
               <tr>
                <td align="center">
                    <td align="center"><font color="black"><br><select>
                     <option value="Present"> P</option>
                     <option value="Absent"> A</option>
               </tr>
               <button type="button"  align = "centre">Back</button>
               <button type="button"  align = "centre">Submit</button>

     </fieldset>
</form>
<script type="text/javascript"> Cufon.now(); </script>
<!-- END PAGE SOURCE -->
</body>
</html>

SMS/templates/SMS/DateSheet.html
<title>Student's Site | Student Home</title>
{% extends "SMS/base.html" %}
{% block content %}
{% load static %}
<div class="container">
<aside>
    <h3>Categories</h3>
    <ul class="categories">
        <li><a href= "{% url 'SMS:ViewTimeTableSudent' StudentId %}" class="m1">Time Table</a></li>
        <li><a href= "{% url 'SMS:ViewDateSheet' StudentId %}" class="m2">Date Sheet</a></li>
        <li><a href= "{% url 'SMS:ViewResult' StudentId %}" class="m3">Result</a></li>
        <li><a href= "{% url 'SMS:SendStudentRequest' StudentId %}" class="m4">Request</a></li>
        <li><a href= "{% url 'SMS:UploadStudentAssignment' StudentId %}" class="m5">Assignments</a></li>
        <li><a href= "{% url 'SMS:StudentAcademicDetail' StudentId %}" class="m6">Academic Detail</a></li>
        <li><a href= "{% url 'SMS:ViewStudentFee'  StudentId%}" class="m7">Fee</a></li>
    </ul>
    </aside>
    <section id="content">
    <div class="inside">
        <h2>Date<span>Sheet</span></h2>
        <table style="font-family: arial, sans-serif; border-collapse: collapse;width: 100%;">
            <tr>
                <th>Date</th>
                <th>Subject</th>
            </tr>
            {% for r in results %}
              {% cycle '<tr>' '' '' '' %}
                <td>{{r.Date}}</td>
                <td>{{r.CourseName}}</td>
              {% cycle '' '' '' '</tr>' %}
            {% endfor %}
          </table>
      </div>
      </section>    
      
    </div>
 {% endblock %}

SMS/templates/SMS/DateSheetT.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Student's Site | Student Home</title>
<meta charset="utf-8">
<link rel="stylesheet" href="css/reset.css" type="text/css" media="all">
<link rel="stylesheet" href="css/style.css" type="text/css" media="all">
<script type="text/javascript" src="js/jquery-1.4.2.min.js" ></script>
<script type="text/javascript" src="js/cufon-yui.js"></script>
<script type="text/javascript" src="js/cufon-replace.js"></script>
<script type="text/javascript" src="js/Myriad_Pro_300.font.js"></script>
<script type="text/javascript" src="js/Myriad_Pro_400.font.js"></script>
<script type="text/javascript" src="js/script.js"></script>
</head>
<body id="page5">
<!-- START PAGE SOURCE -->
<div class="wrap">
  <header>
    <div class="container">
      <h1><a href="#">Student's site</a></h1>
      <nav>
        <ul>
            <li class="current"><a href="TimeTableT.html" class="m1">Time Table</a></li>
            <li><a href="DateSheetT.html" class="m2">Date Sheet</a></li>
            <li><a href="ResultT.html" class="m3">Result</a></li>
            <li><a href="RequestT.html" class="m4">Request</a></li>
            <li><a href="AssignmentsT.html" class="m5">Assignments</a></li>
           
            <li><a href="Payroll.html" class="m7">Payroll</a></li>
            <li><a href="AttendanceT.html" class="m8">Attendance</a></li>
         
      </nav>
    </div>
</header>
<h2>Date<span>Sheet</span></h2>
<form id="contacts-form" action="#">
    <fieldset>
        <div class="field">
            <label>Class:</label>
            <input type="text" value=""/>
        </div>
        <br></br>
        <table border="2" cellspacing="3" align="left">
                <tr>
                 <td align="center">Date
                 <td align="center">Course
                 
                </tr>
                <tr>
                    <td align="center">
                    <td align="center"><font color="black"><br>
                    
                </tr>
                <tr>
                    <td align="center">
                    <td align="center"><font color="black"><br>
                </tr>
                <tr>
                    <td align="center">
                    <td align="center"><font color="black"><br>
                </tr>
                <tr>
                    <td align="center">
                    <td align="center"><font color="black"><br>
                </tr>
                <tr>
                    <td align="center">
                    <td align="center"><font color="black"><br>
                </tr>
                <tr>
                    <td align="center">
                    <td align="center"><font color="black"><br>
                </tr>
                <tr>
                    <td align="center">
                    <td align="center"><font color="black"><br>
                </tr>
                <button type="button"  align = "centre">Back</button>
     </fieldset>
</form>
<script type="text/javascript"> Cufon.now(); </script>
<!-- END PAGE SOURCE -->
</body>
</html>

SMS/templates/SMS/Result.html
<title>Student's Site | Student Home</title>
{% extends "SMS/base.html" %}
{% block content %}
{% load static %}
<div class="container">
  <aside>
    <h3>Categories</h3>
    <ul class="categories">
      <li><a href= "{% url 'SMS:ViewTimeTableSudent' StudentId %}" class="m1">Time Table</a></li>
        <li><a href= "{% url 'SMS:ViewDateSheet' StudentId %}" class="m2">Date Sheet</a></li>
        <li><a href= "{% url 'SMS:ViewResult' StudentId %}" class="m3">Result</a></li>
        <li><a href= "{% url 'SMS:SendStudentRequest' StudentId %}" class="m4">Request</a></li>
        <li><a href= "{% url 'SMS:UploadStudentAssignment' StudentId %}" class="m5">Assignments</a></li>
        <li><a href= "{% url 'SMS:StudentAcademicDetail' StudentId %}" class="m6">Academic Detail</a></li>
        <li><a href= "{% url 'SMS:ViewStudentFee'  StudentId%}" class="m7">Fee</a></li>
    </ul>
  </aside>
  <section id="content">
    <div class="inside">
      
<h2>Result <span></span></h2>
<form id="contacts-form" action="#">
  <fieldset>
    <div class="field">
      <label>class:</label>
      <input type="text" value=""/>
    </div>
    <div class="field">
        <label>Section:</label>
        <input type="text" value=""/>
     </div>
     <div class="field">
        <label>Registration No:</label>
         <input type="text" value=""/>
    </div>
    <div class="field">
        <label>Subject:</label>
            <select>
                <option value="Math">Math</option>
                <option value="English">English</option>
            </select>
    </div>
            <div class="field">
        <label>Marks:</label>
        <input type="text" value=""/>
    </div>
</fieldset>
</form>
    </div>
  </section>

</div>
{% endblock %}

SMS/templates/SMS/TimeTable.html
<title>Student's Site | Student Home</title>
{% extends "SMS/base.html" %}
{% block content %}
{% load static %}
<div class="container">
<aside>
    <h3>Categories</h3>
    <ul class="categories">
      <li><a href= "{% url 'SMS:ViewTimeTableSudent' StudentId %}" class="m1">Time Table</a></li>
      <li><a href= "{% url 'SMS:ViewDateSheet' StudentId %}" class="m2">Date Sheet</a></li>
      <li><a href= "{% url 'SMS:ViewResult' StudentId %}" class="m3">Result</a></li>
      <li><a href= "{% url 'SMS:SendStudentRequest' StudentId %}" class="m4">Request</a></li>
      <li><a href= "{% url 'SMS:UploadStudentAssignment' StudentId %}" class="m5">Assignments</a></li>
      <li><a href= "{% url 'SMS:StudentAcademicDetail' StudentId %}" class="m6">Academic Detail</a></li>
      <li><a href= "{% url 'SMS:ViewStudentFee'  StudentId%}" class="m7">Fee</a></li>
    </ul>
    </aside>
    <section id="content">
    <div class="inside">
      <h2>Time <span>Table</span></h2>
      </div>
      </section>
      
      
    </div>
 {% endblock %}
 

SMS/templates/SMS/articles.html
{% extends "SMS/base.html" %}
{% block content %}
{% load static %}
  <div class="container">
    <aside>
      <h3>Categories</h3>
      <ul class="categories">
        <li><span><a href="#">Programs</a></span></li>
        <li><span><a href="{% url 'SMS:Login' %}">Student</a></span></li>
        <li><span><a href="{% url 'SMS:Login' %}">Teacher</a></span></li>
        <li><span><a href="#">Descriptions</a></span></li>
        <li><span><a href="/admin">Administrator</a></span></li>
        <li><span><a href="#">Basic Information</a></span></li>
        <li><span><a href="#">Vacancies</a></span></li>
        <li class="last"><span><a href="#">Calendar</a></span></li>
      </ul>
      <form action="#" id="newsletter-form">
        <fieldset>
          <div class="rowElem">
            <h2>Newsletter</h2>
            <input type="email" value="Enter Your Email Here" onFocus="if(this.value=='Enter Your Email Here'){this.value=''}" onBlur="if(this.value==''){this.value='Enter Your Email Here'}" >
            <div class="clear"><a href="#" class="fleft">Unsubscribe</a><a href="#" class="fright">Submit</a></div>
          </div>
        </fieldset>
      </form>
      <h2>Fresh <span>News</span></h2>
      <ul class="news">
        <li><strong>June 30, 2010</strong>
          <h4><a href="#">Sed ut perspiciatis unde</a></h4>
          Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque. </li>
        <li><strong>June 14, 2010</strong>
          <h4><a href="#">Neque porro quisquam est</a></h4>
          Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit consequuntur magni. </li>
        <li><strong>May 29, 2010</strong>
          <h4><a href="#">Minima veniam, quis nostrum</a></h4>
          Uis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae. </li>
      </ul>
    </aside>
    <section id="content">
      
      <div class="inside">
        <h2>Articles</h2>
        <ul class="articles">
          <li><img src="images/icon1.png">
            <h4><a href="article.html">Article 1</a></h4>
            Eusus consequam vitae habitur amet nullam vitae condis phasellus sed justo. Orcivel mollis intesque eu sempor ridictum a non laorem lacingilla wisi.</li>
          <li><img src="images/icon2.png">
            <h4><a href="#">Article 2</a></h4>
            Eusus consequam vitae habitur amet nullam vitae condis phasellus sed justo. Orcivel mollis intesque eu sempor ridictum a non laorem lacingilla wisi.</li>
          <li><img src="images/icon3.png">
            <h4><a href="#">Article 3</a></h4>
            Eusus consequam vitae habitur amet nullam vitae condis phasellus sed justo. Orcivel mollis intesque eu sempor ridictum a non laorem lacingilla wisi.</li>
          <li><img src="images/icon4.png">
            <h4><a href="#">Article 4</a></h4>
            Eusus consequam vitae habitur amet nullam vitae condis phasellus sed justo. Orcivel mollis intesque eu sempor ridictum a non laorem lacingilla wisi.</li>
          <li><img src="images/icon5.png">
            <h4><a href="#">Article 5</a></h4>
            Eusus consequam vitae habitur amet nullam vitae condis phasellus sed justo. Orcivel mollis intesque eu sempor ridictum a non laorem lacingilla wisi.</li>
          <li><img src="images/icon6.png">
            <h4><a href="#">Article 6</a></h4>
            Eusus consequam vitae habitur amet nullam vitae condis phasellus sed justo. Orcivel mollis intesque eu sempor ridictum a non laorem lacingilla wisi.</li>
        </ul>
      </div>
    </section>
  </div>
</div>
{% endblock %}

SMS/templates/SMS/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Student's Site</title>
<meta charset="utf-8">

{% load static %}
<link rel="shortcut icon"  href="{% static 'SMS/SMS_Icon2.ico' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'SMS/css/reset.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'SMS/css/style.css' %}" media="all">
<script type="text/javascript" src="{% static 'SMS/js/jquery-1.4.2.min.js' %}" ></script>
<script type="text/javascript" src="{% static 'SMS/js/cufon-yui.js' %}"></script>
<script type="text/javascript" src="{% static 'SMS/js/cufon-replace.js' %}"></script>
<script type="text/javascript" src="{% static 'SMS/js/Myriad_Pro_300.font.js' %}"></script>
<script type="text/javascript" src="{% static 'SMS/js/Myriad_Pro_400.font.js' %}"></script>
<script type="text/javascript" src="{% static 'SMS/js/script.js' %}"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script>
  function GoogleSearch(){
    query = document.getElementById("SearchInput").value
    window.location = "https://www.google.com/search?source=hp&ei=j1fNXPCxO4XYaMrIiUA&q=" + query + "&btnK=Google+Search&oq=list&gs_l=psy-ab.3..35i39j0i67l4j0i20i263j0l2j0i131j0.3019.3633..4176...3.0..0.262.1262.2-5......0....1..gws-wiz.....6.HJ-2xe5K7pk"
  }
</script>
</head>
<body id="page1">
<!-- START PAGE SOURCE -->
<div class="wrap">
  <header>
    <div class="container">
      <h1><a href="#">School Management System</a></h1>
      <nav>
        <ul>
          <li ><a href="{% url 'SMS:index' %}" class="m1">Home Page</a></li>
          <li><a href="{% url 'SMS:About'  %}" class="m2">About Us</a></li>
          <li><a href="{% url 'SMS:Articles' %}"  class="m3">Our Articles</a></li>
          <li><a href="{% url 'SMS:Contact_Us' %}" class="m4">Contact Us</a></li>
          <li class="last"><a href="{% url 'SMS:Sitemaps' %}"class="m5">Sitemap</a></li>
        </ul>
      </nav>
      <form action="#" id="search-form">
        <fieldset>
          <div class="rowElem">
            <input id = "SearchInput" type="text">
            <a onclick="GoogleSearch()" href="#">Search</a></div>
        </fieldset>
      </form>
    </div>
  </header>
  {% block content %}{% endblock %}
  
</div>
<footer>
  <div class="footerlink">
    <p class="lf">Copyright &copy; 2010 <a href="#">SiteName</a> - All Rights Reserved</p>
    <p class="rf">Design by <a href="http://www.templatemonster.com/">TemplateMonster</a></p>
    <div style="clear:both;"></div>
  </div>
</footer>
<script type="text/javascript"> Cufon.now(); </script>
<!-- END PAGE SOURCE -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

SMS/templates/SMS/sitemap.html
{% extends "SMS/base.html" %}
{% block content %}
{% load static %}
  <div class="container">
    <aside>
      <h3>Categories</h3>
      <ul class="categories">
        <li><span><a href="#">Programs</a></span></li>
        <li><span><a href="{% url 'SMS:Login' %}">Student</a></span></li>
        <li><span><a href="{% url 'SMS:Login' %}">Teacher</a></span></li>
        <li><span><a href="#">Descriptions</a></span></li>
        <li><span><a href="/admin">Administrator</a></span></li>
        <li><span><a href="#">Basic Information</a></span></li>
        <li><span><a href="#">Vacancies</a></span></li>
        <li class="last"><span><a href="#">Calendar</a></span></li>
      </ul>
      <form action="#" id="newsletter-form">
        <fieldset>
          <div class="rowElem">
            <h2>Newsletter</h2>
            <input type="email" value="Enter Your Email Here" onFocus="if(this.value=='Enter Your Email Here'){this.value=''}" onBlur="if(this.value==''){this.value='Enter Your Email Here'}" >
            <div class="clear"><a href="#" class="fleft">Unsubscribe</a><a href="#" class="fright">Submit</a></div>
          </div>
        </fieldset>
      </form>
      <h2>Fresh <span>News</span></h2>
      <ul class="news">
        <li><strong>June 30, 2010</strong>
          <h4><a href="#">Sed ut perspiciatis unde</a></h4>
          Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque. </li>
        <li><strong>June 14, 2010</strong>
          <h4><a href="#">Neque porro quisquam est</a></h4>
          Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit consequuntur magni. </li>
        <li><strong>May 29, 2010</strong>
          <h4><a href="#">Minima veniam, quis nostrum</a></h4>
          Uis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae. </li>
      </ul>
    </aside>
    <section id="content">
      
      <div class="inside">
        <h2>Site <span>Map</span></h2>
        <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur.</p>
        <ul class="sitemap">
          <li><a href="#">Home</a></li>
          <li><a href="#">About Us</a></li>
          <li><a href="#">Articles</a>
            <ul>
              <li><a href="article.html">Article 1</a></li>
              <li><a href="#">Article 2</a></li>
              <li><a href="#">Article 3</a></li>
            </ul>
          </li>
          <li><a href="#">Contact Us</a></li>
          <li><a href="#">Site Map</a></li>
        </ul>
        <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.</p>
        <p class="p0">Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.</p>
      </div>
    </section>
  </div>
</div>
{% endblock %}